version: '3.8'

services:
  postgres:
    networks:
        - cesizen-network
    build: .
    container_name: postgres-db
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    ports:
      - "6432:6432"
    env_file: ".env"
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      POOL_MODE: ${POOL_MODE:-transaction}
      MAX_CLIENT_CONN: ${MAX_CLIENT_CONN:-100}
      DEFAULT_POOL_SIZE: ${DEFAULT_POOL_SIZE:-20}
      MIN_POOL_SIZE: ${MIN_POOL_SIZE:-5}
      RESERVE_POOL_SIZE: ${RESERVE_POOL_SIZE:-5}
      LISTEN_ADDRESS: ${LISTEN_ADDRESS:-*}
      LISTEN_PORT: ${LISTEN_PORT:-6432}
      AUTH_TYPE: ${AUTH_TYPE:-scram-sha-256}
    networks:
      - cesizen-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -h pgbouncer -p 6432 -U ${DB_USER} -d ${DB_NAME}"]
        interval: 10s
        timeout: 5s
        retries: 5
  api:
    container_name: api
    networks:
        - cesizen-network
    build:
      context: ${API_BUILD_CONTEXT}
      dockerfile: ${API_DOCKERFILE_PATH}
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - ${API_ENV_FILE}
    
    ports:
      - "${API_PORT}:8080"
    restart: unless-stopped
    depends_on:
      pgbouncer:
        condition: service_healthy
volumes:
  postgres-data:
    driver: local
networks:
  cesizen-network:
    driver: bridge